spring.application.name=bibliotheque-api


# ==========================================
# MySQL Database Connection Settings
# ==========================================
spring.datasource.url=jdbc:mysql://localhost:3306/bibliotheque?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=@.@Cmbz7
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# JPA / Hibernate Configurations
# ==========================================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect